const String myQuery = r'''
    query Me {
      me {
        id
        firstname
        lastname
        email
        company_id
        company_name
        fnln
        dept
        designation
        account_type
        lat
        log
        gcm_id
        img
        role
        reset_id
        conference_id
        created_by
        updated_by
        updated_at
        class
        section
        campus
        company
        parent_id
        student_id
        relationship
        login_id
        roll_number
        birth_day
        mobile_otp
        email_otp
        verified
        last_login_address
        gender
        blood_group
        marital_status
        nickname
        present_address
        permanent_address
        employee_id
        nid
        intro
        father_name
        mother_name
        do_not_disturb
        screen_time_today
        face_detection
        finger_detection
        vacation_mode
        in_time_today
        out_time_today
        phone_optional
        school
        short_id
        mute
        short_id_guest
        customer_id
        timezone
        email_send_time
        is_active
        is_delete
        is_busy
        login_total
        login_attempt
        mute_all
        eod_report
        ticket_report
        digest_email
        sso
        phone
        device
        access
        pin_access
        unpin_access
        fcm_id
        student_list
        parent_list
        relationship_map
        user_friend_list
        connected_device
        blocked_list
        interests
        company_list
        student_link
        last_login
        email_otp_created_at
        createdat
        createdAt
        updatedAt
        erpNext
        erpNextPass
        erpNextRoles
        multi_company
      }
    }
  ''';
